### ISSUE TITLE
Again shape mismatch error

### ISSUE THREAD

**Issue by Jongsu020509** [zblz/naima#202]
Hi,

I got a new error message for shape mismatch bellow:

Traceback (most recent call last):
  File "IC_Syn_SED.py", line 86, in <module>
    interactive=False
  File "/home/helab/anaconda2/lib/python2.7/site-packages/naima/core.py", line 562, in run_sampler
    sampler, pos = get_sampler(**kwargs)
  File "/home/helab/anaconda2/lib/python2.7/site-packages/naima/core.py", line 523, in get_sampler
    sampler, pos = _run_mcmc(sampler, p0, nburn)
  File "/home/helab/anaconda2/lib/python2.7/site-packages/naima/core.py", line 159, in _run_mcmc
    for i, out in enumerate(sampler.sample(pos, iterations=nrun)):
  File "/home/helab/anaconda2/lib/python2.7/site-packages/emcee/ensemble.py", line 343, in sample
    state, accepted = move.propose(model, state)
  File "/home/helab/anaconda2/lib/python2.7/site-packages/emcee/moves/red_blue.py", line 104, in propose
    state = self.update(state, new_state, accepted, S1)
  File "/home/helab/anaconda2/lib/python2.7/site-packages/emcee/moves/move.py", line 43, in update
    old_state.blobs[m1] = new_state.blobs[m2]
ValueError: shape mismatch: value array of shape (12,) could not be broadcast to indexing result of shape (12,2)

In this case, I can not understand and solve...
Please help me to solve this.

Thanks.

**Comment by zblz** [comment]
If you are still using emcee 3 can you try it with emcee 2? The API is not compatible, and Naina does not support version 3 yet, so it is unlikely that you'll be able to fix it with simple changes.

**Comment by zblz** [comment]
This should be now fixed with #214
