### ISSUE TITLE
weakref pickling Error

### ISSUE THREAD

**Issue by zblz** [zblz/naima#72]
After changin internal data to QTable, running with multithreading on some scripts (not on the tests!) returns:

```
Traceback (most recent call last):
  File "./rxj1713_naima.py", line 270, in <module>
    main(sys.argv)
  File "./rxj1713_naima.py", line 221, in main
    data_sed=True)
  File "/home/vzabalza/Dropbox/projects/naima/naima/core.py", line 397, in run_sampler
    sampler, pos = get_sampler(**kwargs)
  File "/home/vzabalza/Dropbox/projects/naima/naima/core.py", line 363, in get_sampler
    sampler, pos = _run_mcmc(sampler, p0, nburn)
  File "/home/vzabalza/Dropbox/projects/naima/naima/core.py", line 116, in _run_mcmc
    for i, out in enumerate(sampler.sample(pos, iterations=nrun)):
  File "/home/vzabalza/.local/lib/python3.4/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/home/vzabalza/.local/lib/python3.4/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/home/vzabalza/.local/lib/python3.4/site-packages/emcee/interruptible_pool.py", line 94, in map
    return r.get(self.wait_timeout)
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 383, in _handle_tasks
    put(task)
  File "/usr/lib/python3.4/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'weakref'>: attribute lookup weakref on builtins failed
```

**Comment by cdeil** [comment]
Do you have a short self-contained example showing why `QTable` doesn't work? Maybe it can be fixed.
